// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hospital.Models;

public partial class Appointment
{
    public string AppointmentId { get; set; }


    [ForeignKey("Patient")]
    public string PatientId { get; set; }
    public  Patient? Patient { get; set; }

    [ForeignKey("Doctor")]
    public string DoctorId { get; set; }
    public Doctor? Doctor { get; set; }

    public DateTime Date { get; set; }

    public TimeOnly Time { get; set; }


    public Prescription? Prescription;
}