// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hospital.Models;

public partial class Bill
{
    public string BillId { get; set; }

    public DateTime Date { get; set; }

    public string PatientId { get; set; }

    public int RoomCharges { get; set; }

    public int DoctorCharges { get; set; }

    public int MedicineCharges { get; set; }

   
    public  Patient? Patient { get; set; }

    public  Payment? Payment { get; set; }
}