// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hospital.Models;

public partial class Department
{
    public string DepartmentId { get; set; }

    public string Name { get; set; }

    public string Location { get; set; }

    public  ICollection<Doctor> Doctors { get; set; } 

    public  ICollection<Nurse> Nurses { get; set; } 
}