// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hospital.Models;

public partial class Doctor
{
    public string DoctorId { get; set; }

    public string Name { get; set; }

    public string Specialization { get; set; }

    public string Address { get; set; }

    public string DepartmentId { get; set; }

    public string DoctorPhone { get; set; }

    public string DoctorEmail { get; set; }
    public ICollection<Appointment> Appointments { get; set; }

    public  Department? Department { get; set; }




    public ICollection<Prescription> Prescriptions { get; set; }


    public ICollection<DoctorSurgery> DoctorSurgeries { get; set; }
}