// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hospital.Models;

public partial class Medicine
{
    public string MedicineId { get; set; }

    public string Name { get; set; }

    public int Price { get; set; }

    public int Quantity { get; set; }

    public  ICollection<PreMed> PreMeds { get; set; }
}