// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hospital.Models;

public partial class Patient 
{
    public string PatientId { get; set; }

    public string FullName { get; set; }

    public string Gender { get; set; }

    public DateTime Dob { get; set; }

  

    public string PatientPhone { get; set; }

    public string PatientHistory { get; set; }

    public string RoomId { get; set; }
    public Room? Room { get; set; }

    public ICollection<Appointment> Appointments { get; set; }

    public ICollection<Bill> Bills { get; set; }



    public ICollection<Prescription> Prescriptions { get; set; }



    public ICollection<Surgery> Surgeries { get; set; }
}