// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hospital.Models;

public partial class Payment
{
    public string PaymentId { get; set; }

    public string BillId { get; set; }

    public string Type { get; set; }

    public string Status { get; set; }

    public Bill Bill { get; set; }
}