// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hospital.Models;

public partial class Prescription
{
    public string prescriptionId { get; set; }

    public string  DiagonsisDescription { get; set; }
    public DateTime Date { get; set; }

    public string PatientId { get; set; }
    public Patient Patient { get; set; }

    public string DoctorId { get; set; }
    public Doctor Doctor { get; set; }

    public ICollection<PreMed> PreMeds { get; set; }


    public string AppointmentId { get; set; }
    public Appointment  Appointment { get; set; }
    ICollection<Scan>  Scans { get; set; } 
}