// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hospital.Models;

public partial class Room
{
    public string RoomId { get; set; }

    public string Location { get; set; }

    public string Type { get; set; }

    public string Status { get; set; }

  
    public  ICollection<Patient> Patients { get; set; }
    public ICollection<Surgery> Surgeries{ get; set; }
   
}